### ISSUE TITLE
DB missing ?

### ISSUE THREAD

**Issue by buildpress** [octobercms/test-plugin#10]
Hi,

I wanted to check how relationships are set-up but after FTP'ing and run "Plaground" October tells me: 

SQLSTATE[HY000]: General error: 1 no such table: october_test_people (SQL: select count(*) as aggregate from "october_test_people")

I also see no DB available. Am i missing something?
Thanks for your anwer,

Jasper

**Comment by mahony0** [comment]
logout and re-login to backend. it'll install automatically

**Comment by buildpress** [comment]
Ah, great thanks. That worked :+1:
