### ISSUE TITLE
UI issue: unnecessary scroll bar

### ISSUE THREAD

**Issue by gergo85** [octobercms/test-plugin#105]
![issue](https://user-images.githubusercontent.com/2959112/145601253-1f7a658c-87a3-4a98-bdcd-26f7dd7b3f19.PNG)

**Comment by daftspunk** [comment]
I can't replicate this on Windows + Chrome. However, have switched the CSS from `overflow: auto` to `overflow-y: auto`. It will be available in the next release v2.1.24

Hopefully it helps
