### ISSUE TITLE
Error creating Role on Pivot model tab

### ISSUE THREAD

**Issue by igor-tv** [octobercms/test-plugin#107]
Tested on OCMS v2.2.32
```Call to a member function getId() on null```

<img width="1374" alt="Снимок экрана 2022-07-13 в 15 01 39" src="https://user-images.githubusercontent.com/6777469/178729473-d437afe9-0f95-434d-ba7d-bfdbaa44365c.png">

**Comment by daftspunk** [comment]
Hi @igor-tv, this button is left intentionally as a placeholder for a feature that is not supported but could be introduced in the future. We could hide it but want to leave it there as a reminder.
