### ISSUE TITLE
Undefined variable: widget

### ISSUE THREAD

**Issue by pedrojuntadigital** [octobercms/test-plugin#21]
When I try to open the post it throws an exception.

Undefined variable: widget
![screen shot 2016-10-12 at 13 12 16](https://cloud.githubusercontent.com/assets/22792231/19309562/8aaa4d50-907d-11e6-937d-8581f8a3651f.png)

**Comment by daftspunk** [comment]
Unable to replicate. Please provide exact steps taken. Make sure the plugin is freshly installed. Eg:

```
# php artisan plugin:refresh october.test
Rolled back: October.Test
Reinstalling plugin...
October.Test
 - v1.0.1:  First version of Test
 - v1.0.2:  Create tables
 - v1.0.3:  Seed tables
```

**Comment by apit** [comment]
i'm using build 365 and encountered this too by opening /october/test/posts/update/1
this is the local vars before exception thrown:

![screenshot_377](https://cloud.githubusercontent.com/assets/98901/19757478/410a996c-9c4d-11e6-87e2-5dd5bc4d6e05.jpg)

**Comment by daftspunk** [comment]
Make sure you are using the latest version and [latest edge build](https://octobercms.com/docs/setup/configuration#edge-updates) of October when using this plugin. Then try again.
