### ISSUE TITLE
Error when I want to create or modify a plugin

### ISSUE THREAD

**Issue by gergo85** [octobercms/test-plugin#24]
![error](https://cloud.githubusercontent.com/assets/2959112/19688736/2d8fb396-9acb-11e6-991c-8d484dab598e.jpg)

**Comment by daftspunk** [comment]
Unable to replicate this. Make sure the file path in the error exists. 
1. Open Playground link in menu
2. Click Reviews
3. Click Manage Plugins
4. Click New Plugin
5. Enter random text in all fields
6. Click Create and Close
7. Plugin creates successfully

As per the contribution guidelines, please provide the exact steps you are taking for the issue to occur. This will be used for peer review.

**Comment by gergo85** [comment]
I reinstall the plugin, but I get a same error message.

Steps:
1. Open the Playground page in menu
2. Click the Reviews
3. Click the Manage Plugins
4. And click the New Plugin

But the the Create Theme page works properly.

**Comment by KonstantinObuhov** [comment]
To fix this bug I've changed code on line 29 in plugins/october/test/controllers/Plugins.php like that 
`$config = $this->makeConfig('$/october/test/models/meta/fields.yaml');` , it was
 `$config = $this->makeConfig('$\october\test\models\meta\fields.yaml');`

**Comment by daftspunk** [comment]
Seems legit. PR?
