### ISSUE TITLE
Inserting pivot data fails for fields without default value 

### ISSUE THREAD

**Issue by meysammahfouzi** [octobercms/test-plugin#30]
This is either a bug or a feature that everybody should be aware of. I spent several hours to figure it out because it's been documented nowhere.   

Assuming we have the following pivot data:

        'roles_pivot' => [
            'October\Test\Models\Role',
            'table' => 'october_test_users_roles',
            'pivot' => ['clearance_level', 'is_executive'],
            'timestamps' => true
        ],

The `clearance_level` and `is_executive` fields can be saved into database via the [RelationController](https://octobercms.com/docs/backend/relations#belongs-to-many-pivot), only if these fields are either `nullable` or have a `default value`:

            $table->string('clearance_level')->nullable();
            $table->boolean('is_executive')->default(false);

So the following fields won't be able to be saved into database:

            $table->string('clearance_level');
            $table->boolean('is_executive');

If this is a known issue, I think it should be documented somewhere.

**Comment by flyingbaba** [comment]
Agree on that, I had this issue from quite a long time age, but don't remember from what version of updates. For now on I have to fill pivot data each time I add new record.

**Comment by daftspunk** [comment]
This isn't really a bug, just MySQL being strict--the default setting now and what we have always recommended. It is a good habit to make your optional columns `nullable`. Sometimes even in addition to a default value because updating a column that has a default, sometimes the system will try to set as NULL and will throw the same error.
