### ISSUE TITLE
Proxy fields relation id null on create.

### ISSUE THREAD

**Issue by RedMarlin** [octobercms/test-plugin#36]
I have an issue with proxy fields. They were working previously (in test plugin and in my own plugin) correctly but I discovered few days ago that they are not working anymore. 
October build: 415
Test plugin: latest (downloaded today)

Steps
1. Click on Create New Person
2. Change view to Proxy Fields
3. Fill in all the necessary data for phone proxy fields and person
4. Create person

Expected behavior:
New Person will be created related to new Phone with all the details you have filled in.

Current behavior:
- The new person will be create correctly
- New phone will be created (all data will be save correctly except for person_id) but without any relation to person.
- person_id column in october_test_phones table is saved as NULL

It works perfectly with Relation Controller, this only happens with Proxy Fields.
Is there a new method to make proxy fields work with current October build or is this a bug?

Thanks!
EDIT: It works correctly with Build 317

**Comment by RedMarlin** [comment]
This is related to OctoberCms more that to test plugin

**Comment by tim0991** [comment]
@RedMarlin How it works? In my project, the phone.person_id is still null when i create person
