### ISSUE TITLE
BUILD420 issue: Extended models in relation with pivot fields contain extended fields #3265

### ISSUE THREAD

**Issue by flyingbaba** [octobercms/test-plugin#47]
Issue description: 
It was ok before to use an

        self::extend(
            function ($model) {
                // Implement the translatable behavior
                $model->implement[] = '@Renatio.SeoManager.Behaviors.SeoModel';
            }
        );

on a model and later to have a relation to this model with pivot fields. These extended fields were rendered in a forms models controller not from another models relation. Now together with pivot fields I have a extended fields. How to get rid of them ?
------------------------------
Steps to reproduce the issue: 
1. Go to https://github.com/flyingbaba/oc-test-plugin clone or download . (Should be enouth to test: go to Playground -> Trees -> Edit any Category, try to add relation to it)
2. Don't forget plugin.php require public $require = ['Renatio.SeoManager'];
3. updates/version.yaml - contain new record and creates new table: create_categories_countries_table.php called: october_test_categories_countries
4. Model Country is extended with $model->implement[] = '@Renatio.SeoManager.Behaviors.SeoModel';
5. Added default_columns.yaml to models/country/ . Used in relation_config.yaml for lists. 
6. Added new field to models/category/fields.yaml
7. Added new partial to controllers/categories/_field_countries.htm
8. Added relation config to controllers/categories/config_relation.yaml + added relation config to controllers/Categories.php
9. Ready to be tested ! Issue is here: Playground -> Trees -> Edit any Category when adding any new country SEO fields are rendered.

**Comment by flyingbaba** [comment]
Please close this issue, new update is released for Renatio.Seomanager and the issue is no longer there

**Comment by daftspunk** [comment]
Thanks for following this up
