### ISSUE TITLE
[question] grabbing states from a different table in the countries demo

### ISSUE THREAD

**Issue by smokeyfro** [octobercms/test-plugin#49]
Hi Samuel,

Thanks a lot for the test plugin. I just found it and it's already helping me wrap my head around the internals of October (which I'm thoroughly enjoying using).

In the countries demo, where the states are populated based on the country field selection, I'm trying to figure out how to adapt the getStateOptions function to grab the list from a different table (states)? 

Any ideas? Also, if you'd prefer I post this in the October forums, just let me know.

TIA, 
Chris

**Comment by Cleanse** [comment]
You would need to create a 'states' db table and create a relationship in the `Country` model. Then in your `fields.yaml`, add the `type: relation`. This should create a drop down or select box depending on if it was setup as a one or many relationship (https://octobercms.com/docs/backend/forms#widget-relation).

**Comment by daftspunk** [comment]
The answer from @Cleanse above is what I would also suggest. Thanks
