### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'avc_october.october_test_people' doesn't exist

### ISSUE THREAD

**Issue by richlove1** [octobercms/test-plugin#7]
Hi

I get this error after extracting the archive to october/test. Do I need to do a plugin install to get this working?

Thanks
Rich

**Comment by richlove1** [comment]
Sorted by running php artisan plugin:refresh :)

**Comment by pablorq** [comment]
With Docker:
```
sudo docker exec [container_name] artisan plugin:refresh october.test
```
