### ISSUE TITLE
Form widgets are not bound to popups

### ISSUE THREAD

**Issue by LarryBarker** [octobercms/test-plugin#73]
When trying to modify list behavior to use the `recordOnClick` property to execute JavaScript so a popup is rendered with a record update form, form widgets are not bound to the controller.

1. Navigate to the test plugin
2. Open the Posts controller
3. Select the comments tab
4. Click on a comment to render the popup
5. Attempt to change the comment's post relationship using the relation widget
6. An error is thrown:

![image](https://user-images.githubusercontent.com/28734844/59723875-78b64a80-91ed-11e9-95e9-9b31859f9d99.png)

I discovered this issue when trying to replicate this behavior in my own plugin but using a file upload widget. Everything works as expected with the exception that after you pick a file from the file browser and it completes uploading, the widget displays an error:
![image](https://user-images.githubusercontent.com/28734844/59723966-d8acf100-91ed-11e9-877f-9b3c1b761328.png)

My code is exactly the same as the post controller's:

```
public function onUpdate()
    {
        $this->asExtension('FormController')->update_onSave(post('record_id'));
        return $this->listRefresh();
    }

    public function onUpdateForm()
    {       
        $this->asExtension('FormController')->update(post('record_id'));
        $this->vars['recordId'] = post('record_id');
        return $this->makePartial('update_form');
    }
```

**Comment by LarryBarker** [comment]
I found [https://github.com/octobercms/october/issues/2727](https://github.com/octobercms/october/issues/2727) last night and spent some time this morning working on this. I was able to get the upload widget working in my case with some modifications to my original code. I borrowed heavily from the RelationController behavior.

```
public function onUpdate()
    {
        $recordId = post('record_id');

        $model = $this->formFindModelObject($recordId);
        $this->initForm($model);

        $this->formBeforeSave($model);
        $this->formBeforeUpdate($model);

        $modelsToSave = $this->prepareModelsToSave($model, $this->updateAdaptorFormWidget->getSaveData());
        Db::transaction(function () use ($modelsToSave) {
            foreach ($modelsToSave as $modelToSave) {
                $modelToSave->save(null, $this->updateAdaptorFormWidget->getSessionKey());
            }
        });

        $this->formAfterSave($model);
        $this->formAfterUpdate($model);

        Flash::success('Adaptor successfully updated.');
        
        return $this->listRefresh();
    }

    public function onUpdateForm()
    {              
        $this->vars['recordId'] = post('record_id');
        $this->vars['widget'] = $this->createAdaptorFormWidget(post('record_id'));
        return $this->makePartial('update_form');
    }

    protected function createAdaptorFormWidget($id = null)
    {
        $config = $this->makeConfig('$/author/plugin/models/adaptor/fields.yaml');
        if ($id) {
            $config->model = \Author\Plugin\Models\Adaptor::find($id);
        } else {
            $config->model = new \Author\Plugin\Models\Adaptor;
        }
        $widget = $this->makeWidget('Backend\Widgets\Form', $config);
        $widget->bindToController();
        return $widget;
    }
```

Obviously the duplication of the `onUpdate` method from the FormController is not ideal; however, I was unable to use `$this->asExtension('FormController')->update_onSave(post('record_id'));` as I expected as it throws a new error:

![image](https://user-images.githubusercontent.com/28734844/59771370-303f7100-926f-11e9-9062-53936ad9bccf.png)

**Comment by samuelpatro** [comment]
We foundout with @alxy that reruning `$this->asExtension('FormController')->update(post('record_id'));` in construct fixes any issues with widgets.
