### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/test-plugin#9]
Is it possible to limit the nesting depth on the Reorder Channels demo? I'm thinking of a use case whereby a product belongs to a category but you want to be able to sort both products and categories in the same re-order page and would therefore require that products can only be dragged between categories. Any advice would be gratefully appreciated.

**Comment by daftspunk** [comment]
Belated response. There is no way to do this atm, but we could add an option for this if you were to request it via the official channels
