### ISSUE TITLE
$attributeNames not taken in account in backend form model validation

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/test-plugin#98]
adding this into the `people` model,

```php
public $attributeManes = [
        'name' => 'People name',
    ];
```

then create a new people through the playground, leave the name empty and save.

Current validation message stays  `Name field is required`

Validation message expected is `People name field is required`

**Comment by daftspunk** [comment]
Hey @chrisvidal 

Upon closer inspection of this issue, the current behaviour is by design. The attribute name is taken from the field name in the YAML configuration. You can override this by extending the form widget.

Thanks!
